sudo: required

language: node_js

node_js:
  - "7"

services:
  - docker

branches:
  only:
    - master

before_install:
  - npm install -g npm
  - npm config set spin false

install:
  - npm install
  
after_success:
  - sh .travis/deploy_dockerhub.sh
  - test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh

notifications:
  email:
    on_success: change
    on_failure: always